AUDIO_DEVICE_RATE = 44100      # Stereo Mix rate
MODEL_SAMPLE_RATE = 16000

BUFFER_SECONDS = 3.0 # min value for genre
HOP_SECONDS = 0.5

MIN_RMS = 0.002
SMOOTHING_ALPHA = 0.4

MIN_BUFFER_SECONDS = 2.5
MAX_BUFFER_SECONDS = 8.0
BUFFER_GROWTH_RATE = 0.5
BUFFER_SHRINK_RATE = 2.0
CONFIDENCE_THRESHOLD = 0.25
STABILITY_FRAMES = 3

